In [3]:
import pandas as pd
import numpy as np
from datetime import datetime
import re

# Data cleaning

## Processing `paper_references.csv`
Null values in the DOI column are represented as different strings, so we remove all values that do not look like a DOI (do not start witn "10.")

In [17]:
papers_df = pd.read_csv("raw-paper_references.csv")

In [18]:
papers_df['DOI'].replace('^(?!10).*', '', regex=True, inplace=True)
papers_df.head(30)

,ID,valid,No_de_Ref,new_ref,filename,DOI,Title,Year,Journal,Pages,Issue,Abstract,Authors,Volume,Corresponding_author,Country,Country_name
0,1,1,1,1,1-s2.0-S092633731000086X-main,10.1016/j.apcatb.2010.02.030,"""Effect of silver doping on the TiO2 for photo...",2010,APPLIED CATALYSIS B-ENVIRONMENTAL,239,NaN,"""Pure TiO2 and various silver-enriched TiO2 po...","""K. Ko\u010d\u00ed, K. Mat\u011bj\u016f, L. Ob...",96,kamila.koci@vsb.cz,"""CZ,CZ,CZ,CZ,CZ,CZ,CZ,CZ,CZ""","""Czech Republic,Czech Republic,Czech Republic,..."
1,2,1,2,2,10.1016@j.cattod.2009.07.067,10.1016/j.cattod.2009.07.067,"""CO2 reforming into fuel using TiO2 photocatal...",2009,CATALYSIS TODAY,341,NaN,"""It was previously reported that CO2 could be ...","""A. Nishimura, N. Komatsu, G. Mitsui, M. Hirot...",148,nisimura@mach.mie-u.ac.jp,"""JP,JP,JP,JP,AU""","""Japan,Japan,Japan,Japan,Australia"""
2,3,1,3,3,1-s2.0-S0926860X05006125-main,10.1016/j.apcata.2005.08.021,"""Photo reduction of CO2 to methanol using opti...",2005,APPLIED CATALYSIS A-GENERAL,194,NaN,"""Greenhouse gases such as CO2 are the primary ...","""J.C.S. Wu, H-M. Lin ,C-L. Lai""",269,cswu@ntu.edu.tw,"""TW,TW,TW""","""Taiwan,Taiwan,Taiwan"""
3,4,1,4,4,27362718_Photo_reduction_of_CO2_to_methanol_vi...,10.1155/S1110662X05000176,"""Photo reduction of CO2 to methanol via TiO2 p...",2005,INTERNATIONAL JOURNAL OF PHOTOENERGY,115,NaN,"""Greenhouse gas such as CO2 is the primary cau...","""J.C.S. Wu, H-M. Lin ,C-L. Lai""",7,cswu@ntu.edu.tw,"""TW,TW""","""Taiwan,Taiwan"""
4,5,1,5,5,10.1023@A@1011403320301,10.1023/A:1011403320301,"""A new type of photocatalysis initiated by pho...",2000,CATALYSIS SURVEYS FROM JAPAN,107,2,"""ZrO2 has been found to be an effective photoc...","""S. Yoshida, Y. Kohno""",4,artleafs.admin@artleafs.eu,"""JP,JP""","""Japan,Japan"""
5,6,1,6,6,10.1016@S0360-5442(98)00070-X,10.1016/S0360-5442(98)00070-X,"""Photocatalytic reduction of CO2 using TiO2 po...",1999,ENERGY,21,NaN,"""At present, carbon dioxide is considered the ...","""S. Kaneco, H. Kurimoto, Y. Shimizu, K. Ohta ,...",24,kaneco@chem.mie-u.ac.jp,"""JP,JP,JP,JP""","""Japan,Japan,Japan,Japan"""
6,7,1,7,7,10.1016@j.cattod.2009.07.081,10.1016/j.cattod.2009.07.081,"""Photocatalytic reduction of CO2 with H2O on P...",2009,CATALYSIS TODAY,335,NaN,"""A gas&ndash;solid heterogeneous system for so...","""Q-H. Zhang, W-D. Han, Y-H. Hong ,J-G. Yu""",148,qhzhang@ecust.edu.cn,"""CN,CN,CN,CN""","""China,China,China,China"""
7,8,1,8,8,10.1016@j.jcis.2010.12.034,10.1016/j.jcis.2010.12.034,"""Photocatalytic reduction of CO2 in methanol t...",2011,JOURNAL OF COLLOID AND INTERFACE SCIENCE,257,NaN,"""Photocatalytic reduction of CO(2) on CuO-TiO(...","""S. Qin, F. Xin, Y. Liu, X. Yin ,W. Ma """,356,xinf@tju.edu.cn,"""CN,CN,CN,CN,CN""","""China,China,China,China,China"""
8,9,1,9,9,10.1016@j.solmat.2007.06.003,10.1016/j.solmat.2007.06.003,"""Photoreduction of carbon dioxide with H2 and ...",2007,SOLAR ENERGY MATERIALS AND SOLAR CELLS,1765,NaN,"""The photocatalytic reduction of carbon dioxid...","""C-C. Lo, C-H. Hung, C-S. Yuan ,J-F. Wu""",91,ycsngi@mail.nsysu.edu.tw,"""TW,TW,TW,TW""","""Taiwan,Taiwan,Taiwan,Taiwan"""
9,10,1,10,10,10.1007@s10563-009-9065-9,10.1007/s10563-009-9065-9,"""Photocatalytic reduction of greenhouse gas CO...",2009,CATALYSIS SURVEYS FROM ASIA,30,NaN,"""Sun is the Earth&rsquo;s ultimate and inexhau...","""J.C.S. Wu""",13,cswu@ntu.edu.tw,"""TW""","""Taiwan"""
10,11,1,11,11,10.1039@B400326H,10.1039/B400326H,"""Improving photoreduction of CO2 with homogene...",2004,CHEMICAL COMMUNICATIONS,1234,NaN,"""Significantly improved photoconversion Of CO2...","""P. Pathak, M.J. Meziani, Y. Li, L.T. Cureton ...",0,syaping@clemson.edu,"""US,US,US,US,US""","""USA,USA,USA,USA,USA"""
11,12,1,12,12,10.1021@ja910091z,10.1021/ja910091z,"""Efficient and Clean Photoreduction of CO2 to ...",2010,JOURNAL OF THE AMERICAN CHEMICAL SOCIETY,2132,NaN,"""A hybrid enzyme&minus;nanoparticle system is ...","""T.W. Woolerton, S. Sheard, E. Reisner, E. Pie...",132,fraser.armstrong@chem.ox.ac.uk,"""GB,GB,GB,GB,GB,GB""","""UK,UK,UK,UK,UK,UK"""
12,13,1,13,13,10.1016@j.carbon.2006.11.028,10.1016/j.carbon.2006.11.028,"""Preparation of multi-walled carbon nanotube s...",2007,CARBON,717,NaN,"""Multi-walled carbon nanotube (MWCNT) supporte...","""X-H. Xia, Z-J. Jia, Y. Yu, Y. Liang, Z. Wang ...",45,xiaxh@phy.ccnu.edu.cn,"""CN,CN,CN,CN,CN,CN""","""China,China,China,China,China,China"""
13,14,1,14,14,10.1021@ja101318k,10.1021/ja101318k,"""Artificial Photosynthesis over Crystalline Ti...",2010,JOURNAL OF THE AMERICAN CHEMICAL SOCIETY,8398,NaN,"""The mechanism of photocatalytic conversion of...","""C-C. Yang, Y-H. Yu, B. van der Linden, J.C.S....",132,G.Mul@tnw.utwente.nl,"""NL,NL,NL,NL,NL""","""Netherlands,Netherlands,Netherlands,Netherlan..."
14,15,1,15,15,10.1021@ja200804h,10.1021/ja200804h,"""Carbon Nanoparticles as Visible-light Photoca...",2011,JOURNAL OF THE AMERICAN CHEMICAL SOCIETY,4754,NaN,"""Increasing atmospheric CO2 levels have genera...","""L. Cao, S. Sahu, P. Anilkumar, C.E. Bunker, J...",133,christopher.bunker@wpafb.af.mil,"""US,US,US,US,US,US,US,US,US,US""","""USA,USA,USA,USA,USA,USA,USA,USA,USA,USA"""
15,16,1,16,16,10.1016@j.cattod.2010.08.026.pdf,10.1016/j.cattod.2010.08.026,"""Comparison of te pure TiO2 and kaolinite/TiO2...",2011,CATALYSIS TODAY,105,NaN,"""The kaolinite/TiO2 composite was prepared usi...","""K. Ko\u010d\u00ed, V. Mat\u011bjka, P. Kov\u0...",161,kamila.koci@vsb.cz,"""CZ,CZ,CZ,CZ,CZ""","""Czech Republic,Czech Republic,Czech Republic,..."
16,17,1,17,17,10.1007@s11244-007-9022-7,10.1007/s11244-007-9022-7,"""Application of optical-fiber photo for CO2 ph...",2008,TOPICS IN CATALYSIS,131,NaN,"""An optical-fiber photoreactor, comprised of 2...","""J.C.S. Wu, T-H. Wu, T. Chu, H. Huang ,D. Tsai""",47,cswu@ntu.edu.tw,"""TW,TW,TW,TW,TW""","""Taiwan,Taiwan,Taiwan,Taiwan,Taiwan"""
17,18,1,18,18,10.1039@C0EE00780C,10.1039/C0EE00780C,"""CO2 photoreduction at enzyme-modified metal o...",2011,ENERGY & ENVIRONMENTAL SCIENCE,2393,NaN,"""A model system for photoreduction of CO2 to C...","""T.W. Woolerton, S. Sheard. E. Pierce S. W. R...",4,fraser.armstrong@chem.ox.ac.uk,"""GB,GB,US,US,GB""","""UK,UK,USA,USA,UK"""
18,19,1,19,19,10.1021@ja108791u,10.1021/ja108791u,"""Role of water and carbonates in photocatalyti...",2011,JOURNAL OF THE AMERICAN CHEMICAL SOCIETY,3964,NaN,"""Using the electron paramagnetic resonance tec...","""N.M. Dimitrijevic, B.K. Vijayan, O.G. Poluekt...",133,dimitrijevic@anl.gov,"""US,US,US,US,US,US,US""","""USA,USA,USA,USA,USA,USA,USA"""
19,20,1,20,20,10.1016@S1872-20671060199-4,10.1016/S1872-2067(10)60199-4,"""Wavelenght effect on photocatalytic reduction...",2011,CHINESE JOURNAL OF CATALYSIS,812,NaN,"""Photocatalytic reduction of CO2 by water was ...","""K. Koci, K. Zatloukalova, L. Obalova, S. Krej...",32,kamila.koci@vsb.cz,"""CZ,CZ,CZ,CZ,CZ,CZ,CZ,CZ""","""Czech Republic,Czech Republic,Czech Republic,..."
20,21,1,21,21,10.1016@j.fuproc.2010.09.007,10.1016/j.fuproc.2010.09.007,"""Photoinduced activation of CO2 on TiO2 surfac...",2011,FUEL PROCESSING TECHNOLOGY,805,NaN,"""Chemical processes that utilize CO2 emissions...","""V.P. Indrakanti, J.D. Kubicki ,H.H. Schobert""",92,pradeep.iv@gmail.com,"""US,US,US""","""USA,USA,USA"""
21,22,1,22,22,10.1016@j.jclepro.2009.02.016,10.1016/j.jclepro.2009.02.016,"""Photo-catalytic reduction of carbon dioxide w...",2009,JOURNAL OF CLEANER PRODUCTION,1025,NaN,"""CO2 is photo-catalytically reduced to produce...","""Z. Zhao, J.Fan, M. Xie, Z. Wang""",17,zzh1972129@163.com,"""CN,CN,CN,CN""","""China,China,China,China"""
22,23,1,23,23,10.1021@jz9000032,10.1021/jz9000032,"""Visible Light Photoreduction of CO2 Using CdS...",2010,JOURNAL OF PHYSICAL CHEMISTRY LETTERS,48,NaN,"""A series of CdSe quantum dot (QD)-sensitized ...","""C. Wang, R.L. Thompson, J. Baltrus ,C. Matranga""",1,congjun.wang@pp.netl.doe.gov,"""US,US,US,US""","""USA,USA,USA,USA"""
23,24,1,24,24,10.1016@j.apcatb.2009.01.010,10.1016/j.apcatb.2009.01.010,"""Effect of TiO2 particle size on the photocata...",2009,APPLIED CATALYSIS B-ENVIRONMENTAL,494,NaN,"""Pure TiO2 anatase particles with a crystallit...","""K.Koci, L. Obalova, L. Matejova, D.Placa, Z. ...",89,kamila.koci@vsb.cz,"""CZ,CZ,CZ,CZ,CZ,CZ,CZ""","""Czech Republic,Czech Republic,Czech Republic,..."
24,25,1,25,25,10.1007@s11244-006-0100-z,10.1007/s11244-006-0100-z,"""Dye sensitized CO2 reduction over pure and pl...",2007,TOPICS IN CATALYSIS,523,4,"""TiO2 thin and thick films promoted with plati...","""O. Ozcan, F. Yukruk, E.U. Akkaya ,D. Uner""",44,uner@metu.edu.tr,"""TR,TR,TR,TR""","""Turkey,Turkey,Turkey,Turkey"""
25,26,1,26,26,10.1016@j.apcatb.2010.08.015,10.1016/j.apcatb.2010.08.015,"""Photocatalytic reduction of CO2 with H2O on m...",2010,APPLIED CATALYSIS B-ENVIRONMENTAL,386,NaN,"""Photoreduction of CO2 to hydrocarbons is a su...","""Y. Li, W-N. Wang, Z. Zhan, M-H. Woo, M-H. Wu,...",100,liying@uwm.edu,"""US,US,US,US,US,US""","""USA,USA,USA,USA,USA,USA"""
26,27,1,27,27,10.1016@S1010-6030(99)00113-6,10.1016/S1010-6030(99)00113-6,"""Photo-enhanced reduction of carbon dioxide wi...",1999,JOURNAL OF PHOTOCHEMISTRY AND PHOTOBIOLOGY A-C...,117,NaN,"""Photoreduction of gaseous carbon dioxide to c...","""Y. Kohno, H. Hayashi, S. Takenaka, T. Tanaka,...",126,artleafs.admin@artleafs.eu,"""JP,JP,JP,JP,JP,JP""","""Japan,Japan,Japan,Japan,Japan,Japan"""
27,28,1,28,28,Kinetic_study_of_photocatalytic_reduction_of_C...,,"""Kinetic study of photocatalytic reduction of ...",2010,CHEMICAL AND PROCESS ENGINEERING-INZYNIERIA CH...,395,NaN,"""Time dependences of photocatalytic reduction ...","""K.Koci, L. Obalova ,O. Solcova""",31,kamila.koci@vsb.cz,"""CZ,CZ,CZ""","""Czech Republic,Czech Republic,Czech Republic"""
28,29,1,29,29,10.2478@v10026-010-0022-1,10.2478/v10026-010-0022-1,"""Photoreduction of carbon dioxide with hydroge...",2010,POLISH JOURNAL OF CHEMICAL TECHNOLOGY,1,3,"""The photocatalytic reduction of carbon dioxid...","""I. Kocemba, J. Nadajczyk, J. Gralski ,M.I. Sz...",12,ikocemba@p.lodz.pl,"""PL,PL,PL,PL""","""Poland,Poland,Poland,Poland"""
29,30,1,30,30,10.1016@j.catcom.2008.04.004,10.1016/j.catcom.2008.04.004,"""Photoreduction of CO2 over Ruthenium dye-sens...",2008,CATALYSIS COMMUNICATIONS,2073,NaN,"""Metal doped TiO2 catalyst sensitized with RuI...","""T-V. Nguyen, J.C.S. Wu ,C-H. Chiou""",9,cswu@ntu.edu.tw,"""TW,TW,TW""","""Taiwan,Taiwan,Taiwan"""

### Export

In [19]:
papers_df.to_csv("paper_references.csv", index=False, sep=",")

## Processing `catalystdata.csv`

In [4]:
exp_df = pd.read_csv("raw-catalystsdata.csv")

### Cleaning null values
Negative numbers and values that serve as null

In [5]:
exp_df.replace([-1,"-1", 0.0, 9999.99], '', inplace=True)
exp_df.head(30)

,ID,No_de_Ref,Catalyst_name,TiO2_crystal_structure,Catalyst,Support,support_percent,Co_catalyst,co_catalyst_2,co_catalyst_3,...,C4H10_mol_m2h,C5H10_mol_m2h,C5H12_mol_m2h,CH3OH_mol_m2h,C2H5OH_mol_m2h,CH3COH_mol_m2h,HCOOH_mol_m2h,CH2O_mol_m2h,C2H4O2_mol_m2h,timestamp
0,1,1,TiO2,Anatase,TiO2,NaN,,NaN,NaN,NaN,...,,,,0.01,,,,,,0000-00-00 00:00:00
1,2,1,TiO2,Anatase,TiO2,NaN,,Ag,NaN,NaN,...,,,,0.01,,,,,,0000-00-00 00:00:00
2,3,1,Ag/TiO2,Anatase,TiO2,NaN,,Ag,NaN,NaN,...,,,,0.01,,,,,,0000-00-00 00:00:00
3,4,1,Ag/TiO2,Anatase,TiO2,NaN,,Ag,NaN,NaN,...,,,,0.02,,,,,,0000-00-00 00:00:00
4,5,1,Ag/TiO2,Anatase,TiO2,NaN,,Ag,NaN,NaN,...,,,,0.03,,,,,,0000-00-00 00:00:00
5,6,2,TiO2,NaN,TiO2,NaN,,NaN,NaN,NaN,...,,,,,,,,,,0000-00-00 00:00:00
6,7,2,TiO2,NaN,TiO2,NaN,,NaN,NaN,NaN,...,,,,,,,,,,0000-00-00 00:00:00
7,8,3,Cu/TiO2,Anatase,TiO2,NaN,,Cu,NaN,NaN,...,,,,,,,,,,0000-00-00 00:00:00
8,9,4,TiO2,Anatase,TiO2,NaN,,NaN,NaN,NaN,...,,,,,,,,,,0000-00-00 00:00:00
9,10,4,Cu/TiO2,Anatase,TiO2,NaN,,Cu,NaN,NaN,...,,,,,,,,,,0000-00-00 00:00:00
10,11,4,Cu/TiO2,Anatase,TiO2,NaN,,Cu,NaN,NaN,...,,,,,,,,,,0000-00-00 00:00:00
11,12,4,Cu/TiO2,Anatase,TiO2,NaN,,Cu,NaN,NaN,...,,,,,,,,,,0000-00-00 00:00:00
12,13,5,ZrO2,NaN,ZrO2,NaN,,NaN,NaN,NaN,...,,,,,,,,,,0000-00-00 00:00:00
13,14,5,ZrO2,NaN,ZrO2,NaN,,NaN,NaN,NaN,...,,,,,,,,,,0000-00-00 00:00:00
14,15,5,ZrO2,NaN,ZrO2,NaN,,NaN,NaN,NaN,...,,,,,,,,,,0000-00-00 00:00:00
15,16,5,ZrO2,NaN,ZrO2,NaN,,NaN,NaN,NaN,...,,,,,,,,,,0000-00-00 00:00:00
16,17,5,ZrO2,NaN,ZrO2,NaN,,NaN,NaN,NaN,...,,,,,,,,,,0000-00-00 00:00:00
17,18,5,ZrO2,NaN,ZrO2,NaN,,NaN,NaN,NaN,...,,,,,,,,,,0000-00-00 00:00:00
18,19,5,ZrO2,NaN,ZrO2,NaN,,NaN,NaN,NaN,...,,,,,,,,,,0000-00-00 00:00:00
19,20,6,TiO2,Anatase,TiO2,NaN,,NaN,NaN,NaN,...,,,,,,,0.22,,,0000-00-00 00:00:00
20,21,7,Pt/TiO2,P25,TiO2,NaN,,Pt,NaN,NaN,...,,,,,,,,,,0000-00-00 00:00:00
21,22,7,Pt/TiO2,P25,TiO2,NaN,,Pt,NaN,NaN,...,,,,,,,,,,0000-00-00 00:00:00
22,23,8,TiO2,Anatase,TiO2,NaN,,CuO,NaN,NaN,...,,,,,,,,,,0000-00-00 00:00:00
23,24,8,CuO/TiO2,Anatase,TiO2,NaN,,CuO,NaN,NaN,...,,,,,,,,,,0000-00-00 00:00:00
24,25,9,TiO2,P25,TiO2,NaN,,NaN,NaN,NaN,...,,,,,,,,,,0000-00-00 00:00:00
25,26,9,TiO2,P25,TiO2,NaN,,NaN,NaN,NaN,...,,,,,,,,,,0000-00-00 00:00:00
26,27,9,TiO2,P25,TiO2,NaN,,NaN,NaN,NaN,...,,,,,,,,,,0000-00-00 00:00:00
27,28,9,ZrO2,NaN,ZrO2,NaN,,NaN,NaN,NaN,...,,,,,,,,,,0000-00-00 00:00:00
28,29,9,ZrO2,NaN,ZrO2,NaN,,NaN,NaN,NaN,...,,,,,,,,,,0000-00-00 00:00:00
29,30,9,ZrO2,NaN,ZrO2,NaN,,NaN,NaN,NaN,...,,,,,,,,,,0000-00-00 00:00:00

### Cleaning values in field `Masscat_g`
Some values are float (g), others have different measurements corresponding to different concepts or even comments. Filtering out all that do not correspond to grams.

In [9]:
def clean_masscat(masscat):
    try:
        masscat = float(masscat)
        return(masscat)
    
    except ValueError or TypeError:
        return('')
    

exp_df.Masscat_g = exp_df.Masscat_g.apply(clean_masscat)
exp_df.Masscat_g

0        0.1
1        0.1
2        0.1
3        0.1
4        0.1
        ...
6659     0.1
6660    0.02
6661    0.02
6662    0.02
6663    0.02
Name: Masscat_g, Length: 6664, dtype: object

### Aligning values with ontology hierarchies

#### Reactor types

In [19]:
exp_df.Reactor_type.replace(('\s', 'Batch'), '', regex=True, inplace=True)
exp_df.Reactor_type.unique()

array(['Slurry', 'Fixed-bed', 'OpticalFiber', 'Monolithic', 'Membrane',
       'Fluidised-bed', ''], dtype=object)

#### Light Sources

In [11]:
## incompleto, mitad de jerarquía con obi: y la otra con solar:
exp_df.Light_source.replace('\s', '', regex=True, inplace=True)
exp_df.Light_source.unique()

array(['UV', 'Solar', 'Visible', 'UV-Vis', 'SolarSimulator',
       'Monochromatic', 'Vis'], dtype=object)

#### Lamps

In [15]:
exp_df.Lamp.replace({"Mercury(Hg)":"Mercury", 
                              "Xenon(Xe)":"Xenon", 
                              "Solar":"SolarSimulator",  
                              "Not spedified":"", 
                              "Mercury-Xenon(Hg-Xe)":"Mercury-Xenon", 
                              "Tungsten(W)":"Tungsten"}, inplace=True)
exp_df.Lamp.unique()

array(['Mercury', 'Fluorescent', 'Xenon', 'SolarSimulator', 'Halogen', '',
       'Tungsten-Halide', 'Mercury-Xenon', 'Other', 'LED', 'Tungsten',
       nan], dtype=object)

#### Wavelengths

In [13]:
def set_wavelengths(wl):
    try:
        wl = float(wl)
        if (wl) >= 192 and (wl) <= 280:
            return("192-280")
        elif (wl) >= 280 and (wl) <= 315:
            return("280-315")
        elif (wl) >= 315 and (wl) <= 400:
            return("315-400")
        elif (wl) >= 400 and (wl) <= 780:
            return("400-780")
        elif (wl) >= 315 and (wl) <= 780:
            return("315-780")
        elif (wl) >= 280 and (wl) <= 780:
            return("280-780")
        elif (wl) >= 192 and (wl) <= 780:
            return("192-780")
        
    except ValueError:
        wl = wl.replace('192-280(UV-A)', '192-280')
        wl = wl.replace('315-400(UV-C)', '315-400')
        wl = wl.replace('280-315(UV-B)', '280-315')
        return(wl)
    
    except TypeError:
        return('')
    

exp_df.Wavelength_nm = exp_df.Wavelength_nm.apply(set_wavelengths)
exp_df.Wavelength_nm.unique()

array(['192-280', '315-400', '280-315', '400-780', None, '315-780',
       '192-780', '280-780', ''], dtype=object)

### Export

In [20]:
exp_df.to_csv("catalystsdata.csv", index=False, sep=",")